### PR TITLE
Merge in single cell changes and a bunch of other dev work

### PR DESCRIPTION
**Pull request by scharch**

### CODE REVIEW

**Comment by ressy** [comment]
Thanks Chaim.  Will this get an update on Docker too?  (Though lately I've actually been using [my own](https://hub.docker.com/r/jesse08/sonar) from [here](https://github.com/ressy/SONAR) with a couple plotting changes related to #15, but still, it'd be good to have the official version up there if you get a chance.)

**Comment by scharch** [comment]
@ressy you mean [this one](https://hub.docker.com/r/scharch/sonar)? I feel stupid, but I can't figure out how to trigger a manual build...

**Comment by scharch** [comment]
Also, if you wanted to submit a pull request for your plotting fixes.... ;-)

**Comment by ressy** [comment]
Yep that's the one!  Beats me about how to streamline it all (I've still been dragging my feet on properly learning Docker) but I just did a manual update like this from within my repo after pulling in your latest changes and I think it worked:

    docker build -t jesse08/sonar .
    docker login -u jesse08 # with creds from https://hub.docker.com/settings/security
    docker push jesse08/sonar

(EDIT more recently: I needed `docker build --no-cache -t jesse08/sonar .` when building an even newer version as it was caching something somewhere and not getting the latest changes.)

So maybe something like that?  Having it available via Docker has ended up being particularly handy because Snakemake supports it via Singularity, so I can just put `singularity: "docker://whoever/sonar"` in my files and it'll automatically download and cache the image and run SONAR commands inside it.

And yeah I should make a pull request for the plotting thing.  I wasn't sure at first how the change to binning the points instead of using the kernel density in the plots would affect things, but seems like it's been working well for me for a while.

**Pull request merged**
